name: Deploy site

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - master

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Build site
        run: |
          ./render.sh

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output/

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
